from sqlTools.SqlTablesUtils import generateTablesRegistersScript
from sqlTools.FilesManage import clean_scripts_folder
import sqlTools.SqlObjectDefinition as ObjDef
clean_scripts_folder()
generateTablesRegistersScript()

ObjDef.create_script_functions_definition()
ObjDef.create_script_procedures_definition()
ObjDef.create_script_triggers_definition()
ObjDef.create_script_views_definition()